"""Render the data contract as Markdown (docs/data-contract.md is generated from this; never edited by hand)."""

from __future__ import annotations

import json

from pydantic import BaseModel

from sutradhar_schemas.contract import (
    CONTRACT_VERSION,
    NETWORK_INPUT_FIELDS,
    OPTIONAL_INPUT_FIELDS,
    PS_MINIMUM_FIELDS,
    REQUIRED_INPUT_FIELDS,
    CanonicalRecord,
)
from sutradhar_schemas.evidence import CapabilityProfile, EvidenceEnvelope, LeadSummary, RunManifest
from sutradhar_schemas.profile import MappingProfile

_MODELS: tuple[tuple[str, type[BaseModel]], ...] = (
    ("CanonicalRecord", CanonicalRecord),
    ("MappingProfile", MappingProfile),
    ("EvidenceEnvelope", EvidenceEnvelope),
    ("LeadSummary", LeadSummary),
    ("RunManifest", RunManifest),
    ("CapabilityProfile", CapabilityProfile),
)


def _yes(name: str) -> str:
    return "yes" if name in PS_MINIMUM_FIELDS else "no"


def render_contract_markdown() -> str:
    lines = [
        f"# Data contract v{CONTRACT_VERSION}",
        "",
        "Generated by `sutradhar schemas export` from `packages/schemas`. Do not edit by hand.",
        "",
        "## Input fields a mapping profile can target",
        "",
        "| Field | Kind | In the PS minimum list |",
        "|---|---|---|",
    ]
    lines.extend(f"| `{name}` | required | {_yes(name)} |" for name in REQUIRED_INPUT_FIELDS)
    lines.extend(f"| `{name}` | network (needed for correlation) | yes |" for name in NETWORK_INPUT_FIELDS)
    lines.extend(f"| `{name}` | optional | {_yes(name)} |" for name in OPTIONAL_INPUT_FIELDS)
    lines += [
        "",
        "Money is converted to integer satoshis and time to UTC microseconds during ingestion.",
        "",
    ]
    for title, model in _MODELS:
        schema = json.dumps(model.model_json_schema(), indent=2, sort_keys=True)
        lines += [f"## {title}", "", "```json", schema, "```", ""]
    return "\n".join(lines)
